---
title: "ReadMortalityData"
author: "Alan Jackson"
date: "August 6, 2018"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(purrr)
library(lubridate)
library(AnomalyDetection)
library(broom)

options(stringsAsFactors = FALSE)

knitr::opts_chunk$set(echo = TRUE)
```

## Read in the data

```{r read data}
folder="/home/ajackson/Dropbox/Rprojects/MortalityData/Data/"
filename_beg <- "IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_"
filename_end <- "_Y2017M05D19.CSV"

files <- state.name %>%
  str_to_upper() %>%  
  str_replace(" ","_") %>%
  paste0(folder, filename_beg,.,filename_end) %>%
  data_frame(state=state.name, fname=.)

df <- files %>%
  mutate(content=map(fname, ~ read_csv(.x))) %>%
  unnest() %>%
  select(-fname)

```

##  Pull out self-harm and interpersonal violence

Gun violence will live in these numbers. Compare to time series of nearby shootings.

Look for anomalous changes

```{r anomalous violence}

library(AnomalyDetection)

dfviol <- df %>%
  filter(state != location_name) %>% # remove state averages to leave counties
  filter(cause_id==717) %>% # "Self-harm and interpersonal violence"
  filter(sex=="Male") %>% # only look at males
  select(state, location_name, year_id, mx) %>% # drop unneeded variables
  mutate(year_id=dmy(paste0("1-1-", as.character(year_id)))) # turn year into date

#dft <- dfviol %>%
#  group_by(state, location_name) %>%
#  mutate(stddev = sd(mx), rng=max(mx)-min(mx)) %>%
#  summarise(stddev=first(stddev), rng=first(rng), county=first(location_name)) 

dft <- dfviol %>%
  group_by(location_name, state) %>%
  nest() %>%
  mutate(stddev=unlist(map(data, ~sd(.x$mx))),
         rng=unlist(map(data, ~(max(.x$mx) - min(.x$mx)))), 
         pctrng=rng/unlist(map(data, ~(mean(.x$mx)))) ) %>%
  mutate(
    model = map(data,
                ~lm(mx~year_id,
                    data = .x)),
    r_squared = map_dbl(model,
                        ~pluck(glance(.x),
                               "r.squared"))
  ) %>%
  select(location_name, state, stddev, rng, r_squared, pctrng, model, data)

dft %>%
  arrange(r_squared) %>%
  head(10) %>%
  mutate(loc=paste0(state,"_",location_name)) %>%
  unnest(data) %>% 
  ggplot(mapping=aes(x=year_id, y=mx)) +
  geom_line(aes(color=loc)) +
  labs(x="Year", 
       y="Self-harm and interpersonal violence mortality rate",
       color="County",
       title="Top 10 Counties for R-Squared Statistical Fit")
  
  
```


